# Generated by Django 4.2.20 on 2025-05-26 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_category_post_is_active_post_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='near_by',
            field=models.CharField(blank=True, choices=[('school', 'School'), ('hospital', 'Hospital'), ('market', 'Market'), ('bus_stop', 'Bus Stop'), ('park', 'Park'), ('temple', 'Temple'), ('mosque', 'Mosque'), ('church', 'Church'), ('restaurant', 'Restaurant'), ('shopping_mall', 'Shopping Mall'), ('bank', 'Bank'), ('atm', 'ATM'), ('gym', 'Gym'), ('pharmacy', 'Pharmacy'), ('gas_station', 'Gas Station'), ('police_station', 'Police Station')], max_length=255, null=True),
        ),
    ]
