# Generated by Django 4.2.20 on 2025-05-26 02:52

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_post_near_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='near_by',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('school', 'School'), ('hospital', 'Hospital'), ('market', 'Market'), ('bus_stop', 'Bus Stop'), ('park', 'Park'), ('temple', 'Temple'), ('mosque', 'Mosque'), ('church', 'Church'), ('restaurant', 'Restaurant'), ('shopping_mall', 'Shopping Mall'), ('bank', 'Bank'), ('atm', 'ATM'), ('gym', 'Gym'), ('pharmacy', 'Pharmacy'), ('gas_station', 'Gas Station'), ('police_station', 'Police Station')], max_length=255, null=True),
        ),
    ]
