# Generated by Django 4.2.20 on 2025-07-05 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_alter_post_near_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default=1, editable=False, max_length=300, unique=True),
            preserve_default=False,
        ),
    ]
