# Generated by Django 4.2.20 on 2025-05-25 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='purpose',
            field=models.CharField(choices=[('register', 'Register'), ('reset', 'Reset Password'), ('social_login', 'Social Login')], max_length=20),
        ),
    ]
